import NavBar from "@/components/navBar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "#3498db", padding: "5px"}}>
        <NavBar/>
        </header>
        {children}
        <footer style={{backgroundColor: "#2c3e50", padding: "5px"}}><p>© 2024 XYZ Company. All rights reserved.</p></footer>
      </body>
    </html>
  )
}
